### ISSUE TITLE
The environment YML file

### ISSUE THREAD

**Issue by shakythesherpa** [babakkhavari/OnSSET_GIS_Extraction_notebook#3] opened 2022-01-12 04:34 UTC
An environment .yml file needed for generating a fully functioning python 3.7 environment does not seem to work the way it is configured currently in Mac OS X ?

**Comment by babakkhavari** [comment] 2022-01-12 18:54
Hi Shaky,

What error message do you get when trying to install the environment?

**Comment by shakythesherpa** [comment] 2022-01-12 20:15
Bavak,
So the error message is regarding the failure to solving environment.


(base) ssherpa@shakys-MacBook-Pro OnSSET_GIS_Extraction_notebook % conda env create --name OnSSET_extraction --file cluster_gis_extract_env.yml 
Collecting package metadata (repodata.json): done
Solving environment: failed

**Comment by babakkhavari** [comment] 2022-01-13 09:39
I think this may be due to certain builds in the .yml being windows-specific. 

Can you try:

`conda env create --name OnSSET_extraction --file cluster_gis_extract_env.yml --no-builds`

**Comment by shakythesherpa** [comment] 2022-01-13 16:52
Ah ok. I tried the no builds but still getting similar error. 
(base) ssherpa@shakys-MBP OnSSET_GIS_Extraction_notebook % conda env create --name OnSSET_extraction -f cluster_gis_extract_env.yml -no-builds 
Collecting package metadata (repodata.json): done
Solving environment: failed


So based on this [stackoverflow comment](https://stackoverflow.com/questions/55554431/conda-fails-to-create-environment-from-yml/55576493#55576493) I try to run a sed over it. It seems to resolve most of the packages but still unable to resolve some of the following packages.

(base) ssherpa@shakys-MBP OnSSET_GIS_Extraction_notebook % conda env create --name OnSSET_extraction --file env.yml               
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - wincertstore=0.2
  - winpty=0.4.3
  - msys2-conda-epoch=20160418
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-gcc-libgfortran=5.3.0
  - vc=14.1
  - icc_rt=2019.0.0
  - win_inet_pton=1.1.0
  - m2w64-gmp=6.1.0
  - m2w64-gcc-libs=5.3.0
  - pywinpty=0.5.7
  - vs2015_runtime=14.16.27012
  - m2w64-gcc-libs-core=5.3.0

**Comment by babakkhavari** [comment] 2022-01-15 08:40
Perhaps if the YML is simplified it will work. It has been on my to do list for some time now. 

I will try and let you know when I have the new one

**Comment by babakkhavari** [comment] 2022-01-16 17:32
Hi Shaky, 

Can you replace the text in the .yml with the text in this .txt and see if it works? This environment is a simplified version of the old one and hopefully should work.

[new_env.txt](https://github.com/babakkhavari/OnSSET_GIS_Extraction_notebook/files/7877523/new_env.txt)

If the installation works, you then have to change cell 1 in "funcs.py" to read `%run funcs.ipynb` instead of `from ipynb.fs.full.funcs import *`

**Comment by shakythesherpa** [comment] 2022-01-20 04:35
Hi Bavak,
That seem to work. 
However, as you noted when I changed the cell 1 in the OnSSET_cluster_extraction.ipynb (not func.ipynb Is that correct?) I am getting an error about module gdal not found.  However, when I checked I do see gdal was installed when I ran the simplified version of the envrionment file you sent.

Anything else I am missing. Sorry to bug you with this.

**Comment by babakkhavari** [comment] 2022-01-20 08:12
Ah, yes you are right, my mistake.

Change cell 1 in "OnSSET_cluster_extraction.ipynb" to read `%run funcs.ipynb` instead of `from ipynb.fs.full.funcs import *` 

For the gdal import you should be able to replace `import gdal` with `from osgeo import gdal` in the first cell of "funcs.py"

Hopefully the extraction tools should work with this new installation, there might be problems however with regards to different version of packages (in the original .yml, certain versions of packages were forced. In the current .yml the latest version is installed).

**Comment by shakythesherpa** [comment] 2022-01-20 17:49
That worked. Thanks so much for your help Bavak!  Much appreciated.

**Comment by babakkhavari** [comment] 2022-01-25 10:27
Perfect! 

Can you let me know if you manage to run the extraction as intended (unfortunately I do not have a mac) If you do not run into any problems, I might as well push these changes to the repo.

**Comment by shakythesherpa** [comment] 2022-01-26 15:51
Hi Babak,
Yes, that worked with no problem.  It would be good to push the changes to
the repo for MAC OSX users.

Thanks  so much again for your help.

**Comment by babakkhavari** [comment] 2022-01-29 12:36
Great, I will push and close this issue then. Thanks!

**Closed by babakkhavari** 2022-01-29 12:36 UTC
